services:
  db:
    image: mysql:8
    container_name: music_player_db
    env_file: ./server/.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "osilva", "-pskateordie123" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: music_player_server
    env_file: ./server/.env
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    ports:
      - "3500:3500"
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: music_player_client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  db_data:
